--------------------------------------------------------
--  文件已创建 - 星期二-七月-31-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "NEUSOFTOA"."EMPLOYEE" 
   (	"EMPNO" NUMBER(10,0), 
	"EMPCODE" VARCHAR2(10 BYTE), 
	"EMPNAME" VARCHAR2(50 BYTE), 
	"AGE" NUMBER(2,0), 
	"SALARY" NUMBER(10,2), 
	"BIRTHDAY" DATE, 
	"EMPDESC" VARCHAR2(2000 BYTE), 
	"PHOTO" BLOB, 
	"PHOTOCONTENTTYPE" VARCHAR2(100 BYTE), 
	"PHOTOFILENAME" VARCHAR2(100 BYTE), 
	"SEX" VARCHAR2(4 BYTE), 
	"EMPPASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PHOTO") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into NEUSOFTOA.EMPLOYEE
SET DEFINE OFF;
Insert into NEUSOFTOA.EMPLOYEE (EMPNO,EMPCODE,EMPNAME,AGE,SALARY,BIRTHDAY,EMPDESC,PHOTOCONTENTTYPE,PHOTOFILENAME,SEX,EMPPASSWORD) values (5,'01003','小小小',27,2000,to_date('25-JUL-18','DD-MON-RR'),'Hanson boy！！！',null,null,'男',null);
Insert into NEUSOFTOA.EMPLOYEE (EMPNO,EMPCODE,EMPNAME,AGE,SALARY,BIRTHDAY,EMPDESC,PHOTOCONTENTTYPE,PHOTOFILENAME,SEX,EMPPASSWORD) values (22,'01006','cft',27,4000,to_date('26-JUL-18','DD-MON-RR'),'测试',null,null,'男',null);
Insert into NEUSOFTOA.EMPLOYEE (EMPNO,EMPCODE,EMPNAME,AGE,SALARY,BIRTHDAY,EMPDESC,PHOTOCONTENTTYPE,PHOTOFILENAME,SEX,EMPPASSWORD) values (23,'01007','pjcft',27,4000,to_date('26-JUL-18','DD-MON-RR'),'测试',null,null,'男',null);
Insert into NEUSOFTOA.EMPLOYEE (EMPNO,EMPCODE,EMPNAME,AGE,SALARY,BIRTHDAY,EMPDESC,PHOTOCONTENTTYPE,PHOTOFILENAME,SEX,EMPPASSWORD) values (61,'1234','小小哈',18,1800,to_date('11-AUG-18','DD-MON-RR'),'三六九等发是哦积分',null,null,'男',null);
Insert into NEUSOFTOA.EMPLOYEE (EMPNO,EMPCODE,EMPNAME,AGE,SALARY,BIRTHDAY,EMPDESC,PHOTOCONTENTTYPE,PHOTOFILENAME,SEX,EMPPASSWORD) values (2,'01001','小彭',22,3000,to_date('25-JUL-18','DD-MON-RR'),'A good boy!!',null,null,'女',null);
Insert into NEUSOFTOA.EMPLOYEE (EMPNO,EMPCODE,EMPNAME,AGE,SALARY,BIRTHDAY,EMPDESC,PHOTOCONTENTTYPE,PHOTOFILENAME,SEX,EMPPASSWORD) values (41,'01006','小小彭',22,5000,to_date('20-FEB-00','DD-MON-RR'),'棒棒哒！！',null,null,'男',null);
Insert into NEUSOFTOA.EMPLOYEE (EMPNO,EMPCODE,EMPNAME,AGE,SALARY,BIRTHDAY,EMPDESC,PHOTOCONTENTTYPE,PHOTOFILENAME,SEX,EMPPASSWORD) values (4,'01002','小婷',22,5000,to_date('25-JUL-18','DD-MON-RR'),'beautiful girl',null,null,null,null);
Insert into NEUSOFTOA.EMPLOYEE (EMPNO,EMPCODE,EMPNAME,AGE,SALARY,BIRTHDAY,EMPDESC,PHOTOCONTENTTYPE,PHOTOFILENAME,SEX,EMPPASSWORD) values (21,'01005','pjc',27,4000,to_date('26-JUL-18','DD-MON-RR'),'测试',null,null,'男',null);
--------------------------------------------------------
--  DDL for Index SYS_C0011203
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEUSOFTOA"."SYS_C0011203" ON "NEUSOFTOA"."EMPLOYEE" ("EMPNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "NEUSOFTOA"."EMPLOYEE" ADD PRIMARY KEY ("EMPNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
